import Head from 'next/head'
import Image from 'next/image'
import Products from './product'
export default function Home() {
  return (
    <div className='p-[2rem]'>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='p-[4rem] min-h-[100vh] flex flex-col justify-center items-center'>
        <Products/>
      </main>

      <footer className=''>
      </footer>
    </div>
  )
}
